packageExtensions:
    'vuepress@*':
        dependencies:
            '@vuepress/shared-utils': '*'
    'vue-server-renderer@2.7.14':
        dependencies:
            'vue': '^2.7.14'
    '@vuepress/shared-utils@*':
        dependencies:
            'markdown-it-emoji': '*'
            'lru-cache': '*'
            '@vue/component-compiler-utils': '*'
    '@vuepress/markdown-loader@*':
        dependencies:
            '@vuepress/shared-utils': '*'
    '@vuepress/core@*':
        dependencies:
            'escape-html': '*'
nodeLinker: 'node-modules'